### ISSUE TITLE
Definición Poco Entendible

### ISSUE THREAD

**Issue by TitoYus** [alejandrorabadan/gestisimal-entornos#4]
[https://alejandrorabadan.github.io/gestisimal-entornos/gestisimal/AlmacenJson.html](https://alejandrorabadan.github.io/gestisimal-entornos/gestisimal/AlmacenJson.html)

**Comment by TitoYus** [comment]
@lmagarin

**Comment by lmagarin** [comment]
@TitoYus definición de qué? es una documentación de toooooooooooooooooooda una clase

**Comment by lmagarin** [comment]
@alejandro69221 , este commit del issue sólo actualiza .html... ¿dónde los .java?

Además, subes los .class?? Para qué?
