### ISSUE TITLE
Falta Descripción

### ISSUE THREAD

**Issue by TitoYus** [alejandrorabadan/gestisimal-entornos#5]
https://github.com/alejandrorabadan/gestisimal-entornos/blob/6a0dcb7aa2e43e7360b5347dff3b5371163e6bd0/src/gestisimal/AlmacenJson.java#L16
Y revisa lo demás colega :D

**Comment by lmagarin** [comment]
Ese bro @TitoYus  que te has echado este año @alejandrorabadan... debe estar de vacaciones porque ni asoma... 🌞 🍹 🌞 🍹 🌞 🍹 🌞 🍹 🌞 🍹 🌞 🍹 🌞 🍹
